name: flutter_easyloading
description: A clean and lightweight Loading widget for Flutter App, easy to use without context, support iOS and Android.
version: 1.2.1
homepage: https://github.com/huangjianke/flutter_easyloading

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: