name: flutter_easyloading
description: A clean and lightweight Loading widget for Flutter, easy to use without context, support iOSã€Android and Web.
version: 2.0.1
homepage: https://github.com/huangjianke/flutter_easyloading

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
